In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [151]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_a3cd8056bd774324a358f7cbe8750ab3 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='s-AACA_h4KhTEG4FNytVJM2aVIv3UqFtj-10tXU7Wct2',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_a3cd8056bd774324a358f7cbe8750ab3.get_object(Bucket='akhil1999-donotdelete-pr-b8h9n9zmrjekz3',Key='akh.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )



dataset = pd.read_csv(body)

In [152]:
dataset.head()

Age  HeartBeat  Systolic  Diastolic  Sugar  Alert
0   18         49        90         60     80      0
1   18         49        90         60    100      0
2   18         49        90         60    120      0
3   18         49        90         60    140      0
4   18         49        90         60    160      0

In [153]:
x= dataset.iloc[:,:5].values

In [154]:
type(x)

numpy.ndarray

In [155]:
x

array([[ 18,  49,  90,  60,  80],
       [ 18,  49,  90,  60, 100],
       [ 18,  49,  90,  60, 120],
       ..., 
       [ 55,  79, 181, 121, 341],
       [ 55,  79, 181, 121, 361],
       [ 55,  79, 181, 121, 381]])

In [156]:
y= dataset.iloc[:,-1:].values

In [157]:
y

array([[0],
       [0],
       [0],
       ..., 
       [1],
       [1],
       [1]])

In [158]:
from sklearn.model_selection import train_test_split           
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [159]:
import keras 
from keras.models import Sequential 
from keras.layers import Dense 

In [160]:
model=Sequential()

In [161]:
model.add(Dense(input_dim=5,init="random_uniform",activation="relu",output_dim=3))

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="random_uniform", units=3, input_dim=5)`
  if __name__ == '__main__':


In [162]:
model.add(Dense(output_dim=3,init="random_uniform",activation="relu"))

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="random_uniform", units=3)`
  if __name__ == '__main__':


In [163]:
model.add(Dense(output_dim=1,init="random_uniform",activation="sigmoid"))

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", kernel_initializer="random_uniform", units=1)`
  if __name__ == '__main__':


In [164]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [165]:
model.fit(x_train,y_train,epochs=100,batch_size=100)

Epoch 1/100
17600/17600 [==============================] - 1s 47us/step - loss: 0.3000 - acc: 0.9444
Epoch 2/100
17600/17600 [==============================] - 1s 35us/step - loss: 0.1598 - acc: 0.9488
Epoch 3/100
17600/17600 [==============================] - 1s 39us/step - loss: 0.1555 - acc: 0.9488
Epoch 4/100
17600/17600 [==============================] - 1s 35us/step - loss: 0.1517 - acc: 0.9488
Epoch 5/100
17600/17600 [==============================] - 1s 39us/step - loss: 0.1483 - acc: 0.9488
Epoch 6/100
17600/17600 [==============================] - 1s 35us/step - loss: 0.1455 - acc: 0.9488
Epoch 7/100
17600/17600 [==============================] - 1s 38us/step - loss: 0.1429 - acc: 0.9488
Epoch 8/100
17600/17600 [==============================] - 1s 35us/step - loss: 0.1411 - acc: 0.9488
Epoch 9/100
17600/17600 [==============================] - 1s 39us/step - loss: 0.1397 - acc: 0.9488
Epoch 10/100
17600/17600 [==============================] - 1s 39us/step - loss: 0.1387 - a

In [179]:
model.save("project.h5")

In [166]:
y_pred=model.predict(x_test)

In [167]:
l = len(y_pred)
l

4400

In [168]:
y_pred[0]

array([ 0.99823833], dtype=float32)

In [169]:
y_test[0]

array([1])

In [170]:
for i in range(0,l):
    if(y_pred[i] >= 0.5):
        y_pred[i]=int(1)
    else:
        y_pred[i]=int(0)

In [171]:
y_pred=y_pred.astype(int)

In [172]:
from sklearn.metrics import confusion_matrix

In [173]:
matrix = confusion_matrix(y_test,y_pred)
matrix

array([[ 142,   82],
       [  13, 4163]])

In [178]:
pr=model.predict(np.array([[35,75,90,70,80]]))
if(pr > 0.5):
    pr =int(1)
else:
    pr =int(0)
pr    

1

In [180]:
import os
cwd = os.getcwd()
cwd

'/home/dsxuser/work'

In [181]:
get_ipython().system(u'tar -zcvf mymodel.tgz project.h5')

project.h5


In [182]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [183]:
wml_credentials={
  "url": "https://eu-gb.ml.cloud.ibm.com",
  "access_key": "yi9SvHEJjlmangHkOixFukGDIKQUOrpp9XkBs_tlMl5X",
  "username": "e09a4150-fdce-4a5c-b18f-d4c109335258",
  "password": "7613b6aa-afff-40f9-8b49-7aa92080156d",
  "instance_id": "7e0db7eb-7183-48c2-9a41-7ee8aad5b431"
}

In [184]:
client = WatsonMachineLearningAPIClient( wml_credentials )

In [185]:
metadata = {
    client.repository.ModelMetaNames.NAME: "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.5"
}

In [186]:
model_details = client.repository.store_model( model="mymodel.tgz", meta_props=metadata )

In [187]:
model_id = model_details["metadata"]["guid"]
model_deployment_details = client.deployments.create( artifact_uid=model_id, name="deployment" )



#######################################################################################

Synchronous deployment creation for uid: '18eac719-7cb9-4866-9b4b-55444768a22e' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='0ab70037-e182-4128-adbf-f613897dc0c3'
------------------------------------------------------------------------------------------------




In [188]:
scoring_endpoint = client.deployments.get_scoring_url(model_deployment_details)

In [189]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/7e0db7eb-7183-48c2-9a41-7ee8aad5b431/deployments/0ab70037-e182-4128-adbf-f613897dc0c3/online'